### ISSUE TITLE
Issue regarding menu links

### ISSUE THREAD

**Issue by roiveredritesh** [PriyaGhosal/SkillWise#1]
Issue Description:
None of header menus are properly connected with their respective blocks. 
Eg. If I am clicking on courses, nothing is happening there.

Acceptance Criteria:
Menus should be properly link with their respective blocks.

**Comment by PriyaGhosal** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
