### ISSUE TITLE
Footer links not working

### ISSUE THREAD

**Issue by SiddhanthKapoor** [PriyaGhosal/SkillWise#10]
Bug Found : Any of the footer redirecting links are not working , they are bringing me back to the home page.
I would like to work on this issue.
Would love to hear back from you !

**Comment by PriyaGhosal** [comment]
@SiddhanthKapoor 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by SiddhanthKapoor** [comment]
> @SiddhanthKapoor Assigned! Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts. Happy open-source contributing!

Thankyou for assigning me this issue Ma'am , However to work on it I'll need the social handles of your website and it'll be helpful if you also see the other two issues I've created.
THANKYOU !
