### ISSUE TITLE
Enhancement: Increase Font Size of Course Categories for Better Visibility

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#100]
![image](https://github.com/user-attachments/assets/905aa9e1-38d0-4f00-869e-e70457007736)

Assessing the current font size used for course categories.
Increasing the font size to improve visibility and consistency with the "Browse Top Categories" section.
Ensuring that the updated font size aligns with the overall design and aesthetics of the website.
Testing the changes across different devices to confirm readability.
Goal: Enhance user experience by ensuring that course categories are easily readable and visually appealing.

**Comment by ipratiik** [comment]
Assign this issue to me #100. I'll do the rest.

**Comment by codeforlifeee** [comment]
@PriyaGhosal

**Comment by PriyaGhosal** [comment]
@codeforlifeee Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
