### ISSUE TITLE
Enhancement: Increase Font Size of "SkillWise" for Better Visibility

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#101]
The current font size of "SkillWise" appears too small compared to the text "We Provide the Best Online Education," making it less prominent.
Goal: Improve user experience by making "SkillWise" more visually prominent and engaging for visitors.
![image](https://github.com/user-attachments/assets/5a4c3961-1c5e-41f7-99b5-59fdb87f63b8)

**Comment by ipratiik** [comment]
Assign this to me Please! I'll do the rest.

**Comment by PriyaGhosal** [comment]
@codeforlifeee Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
