### ISSUE TITLE
Enhancement: Increase Font Size of Featured Blogs and Featured Courses for Better Visibility

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#102]
![image](https://github.com/user-attachments/assets/538bdcdf-3e63-4832-9abf-5d3df09997db)
![image](https://github.com/user-attachments/assets/f7e32562-f11a-400f-8a30-f62863e2ee7a)
The font size of the "Featured Blogs" section is significantly smaller compared to the "Learn with Articles" heading, making it less noticeable.
Similarly, the font size of the "Featured Courses" section is too small compared to the "Choose Unlimited Courses" heading.
Goal: Enhance user experience by ensuring that both "Featured Blogs" and "Featured Courses" are easily readable and visually engaging.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by AadishSanghai** [comment]
i would like ton work on this issue please assign me this issue
