### ISSUE TITLE
The logo of Finances Does not depicts its true nature it should be replaced 

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#103]
![image](https://github.com/user-attachments/assets/75f3eb4e-2114-42e8-a9d9-c62cc1456d1c)

logo can be replaced with the some better logo for better understanding.

**Comment by Aastha7078** [comment]
Assign it to me

**Comment by PriyaGhosal** [comment]
@codeforlifeee Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by AnshDwivedi03** [comment]
hey can you assign it to me @PriyaGhosal

**Comment by codeforlifeee** [comment]
@PriyaGhosal  This issue is already resolved by someone else so I am closing this issue..
