### ISSUE TITLE
Create a Pre-Website Landing Page

### ISSUE THREAD

**Issue by Tanishka534** [PriyaGhosal/SkillWise#104]
We need to design and implement a simple, engaging landing page that will appear before the main website. The purpose of this page is to inform visitors about the upcoming site launch or gather early interest from users before the website goes live.

**Comment by Tanishka534** [comment]
Please assign this issue to me

**Comment by PriyaGhosal** [comment]
@Tanishka534 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
