### ISSUE TITLE
Fix Broken Navbar/Header Navigation Links in the Project for Improved User Experience

### ISSUE THREAD

**Issue by Mritunjaii** [PriyaGhosal/SkillWise#109]
hi @PriyaGhosal ,

I’ve observed an issue with the navbar/header of your project where clicking on any of the links or buttons (Home, Courses, Blog, Contact, Start Trial) results in an incorrect redirection, taking the user back to the home section instead of the intended sections. This affects the navigation experience and could impact user engagement.
I would like to contribute by diagnosing the problem and implementing a fix to ensure that each link and button in the navbar correctly navigates to its respective section or page. By addressing this issue, we can improve the overall user experience of your project. 

Please assign this issue to me under Hacktoberfest2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
