### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by SiddhanthKapoor** [PriyaGhosal/SkillWise#11]
Bug Found : The website when used on a smaller device , does not show the start a free trial button , which may lure a person to sign up for your website.

Approach -
1. Either the empty space between the logo and nav bar can be used for a Free Trial Button !
2. Or out of the two Get Started buttons one will be assigned to Start your free trial now !
I would like to work on this issue and hear back the better approach from you !

**Comment by PriyaGhosal** [comment]
@SiddhanthKapoor 
This issue (no. #4) already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
