### ISSUE TITLE
Improve Contact Us section

### ISSUE THREAD

**Issue by chaanakyaaM** [PriyaGhosal/SkillWise#110]
![image](https://github.com/user-attachments/assets/9682c3de-56a7-4b77-9249-1d210c79a99a)

The website is looking awesome but the contact us section is off the website design.
I would like to do:
- remove the outline for the input fields.
- improve its layout.
- add consistency to the font
- add interaction with the input field.

@PriyaGhosal ,
Could you  kindly assign this issue to me under Hacktoberfest.
I would send the PR as soon as possible.

**Comment by PriyaGhosal** [comment]
@chaanakyaaM Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
