### ISSUE TITLE
Improvement in Footer Section

### ISSUE THREAD

**Issue by mitgajera** [PriyaGhosal/SkillWise#113]
![image](https://github.com/user-attachments/assets/28efc0fe-4ccc-4fcd-ba8e-299815e8f5dd)

Hey @PriyaGhosal,
I've observed a significant issue with the Footer of your project. It's completely disorganized and is negatively impacting the navigation experience, potentially affecting user engagement. It urgently needs restructuring and styling.
I'm willing to take charge of diagnosing the problem and implementing a solution to resolve it. By addressing this issue, we can significantly enhance the overall user experience of your project.

Please assign this issue to me under Hacktoberfest2024.

**Comment by swati-mishra07** [comment]
@PriyaGhosal can you assign this to me .

**Comment by swati-mishra07** [comment]
@PriyaGhosal i modify this but i can't create a pull request  can you solve it?

**Comment by mitgajera** [comment]
@swati-mishra07 
This issue is already resolved.

**Comment by mitgajera** [comment]
@swati-mishra07 
This issue is already resolved by previous PR.

**Comment by swati-mishra07** [comment]
@mitgajera okay that's why I can't do pr
