### ISSUE TITLE
Enhance Course Category Icons for Better Visual Consistency

### ISSUE THREAD

**Issue by mitgajera** [PriyaGhosal/SkillWise#114]
![Screenshot 2024-10-02 113853](https://github.com/user-attachments/assets/2ad4310b-a4ec-4dab-9ddb-03379b0be48a)

Hey @PriyaGhosal,

I've noticed a usability issue with the icons used for the course categories on your project. The current icons lack consistency in terms of design and relevance to the specific subjects they represent. This may lead to confusion for users and reduce the overall aesthetic appeal of the platform.

I propose updating the icons to more accurately reflect each category while maintaining a cohesive design language across the platform. This change would improve visual clarity, ensure a more professional appearance, and ultimately enhance the user experience.

Please assign this issue to me under Hacktoberfest2024. I'm eager to work on it and provide the necessary improvements!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
