### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by yashksaini-coder** [PriyaGhosal/SkillWise#118]
HI @PriyaGhosal I saw that your readme can definitely improve to have better documentation.

Please assign this issue to me start contributing in this project

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by yashksaini-coder** [comment]
Hi @PriyaGhosal these conflicts came when new PRs were merged into the `main` branch. I raised the PR not so long after the issue was assigned. but as new PRs merged the changes were conflicting with each other.

Not to worry I have raised a new PR #301

**Comment by yashksaini-coder** [comment]
Review this PR and add labels to it. @PriyaGhosal
