### ISSUE TITLE
Footer unresponsive

### ISSUE THREAD

**Issue by SiddhanthKapoor** [PriyaGhosal/SkillWise#12]
Bug Found : The website when used on a smaller device , the footer is not responsive

Approach - We can edit the size of the logo in the footer and put text on side of it to make it look responsive and prettier !

**Comment by PriyaGhosal** [comment]
@SiddhanthKapoor 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
