### ISSUE TITLE
Want to add a copyright page 

### ISSUE THREAD

**Issue by DhruvJohri** [PriyaGhosal/SkillWise#120]
please assign me this issue under hacktoberfest 2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by AnshDwivedi03** [comment]
Hey @PriyaGhosal  kindly assign it to me
