### ISSUE TITLE
 Dark mode needs improvement

### ISSUE THREAD

**Issue by mitgajera** [PriyaGhosal/SkillWise#121]
![image](https://github.com/user-attachments/assets/ca283eb2-b425-402c-b03c-0a5dd6e96f62)        ![image](https://github.com/user-attachments/assets/36cd74e5-ce2e-4e06-9ed9-cf6b467d0c25)

Hi @PriyaGhosal,

I hope this message finds you well. I've noticed several issues that need attention, and I'm eager to address them. I'd like to take on this particular issues which occurres in dark mode.

Please assign this issue to me under Hacktoberfest2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
