### ISSUE TITLE
UI/UX Changes in Navbar

### ISSUE THREAD

**Issue by ira-mane** [PriyaGhosal/SkillWise#127]
Changes can be made in Navbar styling and UI 
Also, the navbar is not constant on every page, the search tab is only there on the home page.
![image](https://github.com/user-attachments/assets/0c14b83d-2548-48ff-b54e-5d82bcbe5768)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by vishalgupta8982** [comment]
can you assign this issue to me?
