### ISSUE TITLE
Add .gitignore file to the project and remove node_modules from the repository

### ISSUE THREAD

**Issue by AnandRP2030** [PriyaGhosal/SkillWise#128]
The project currently lacks a `.gitignore` file, and the `node_modules` folder is being tracked in the repository.

 A `.gitignore` file helps to specify which files and directories to ignore when committing code to the repository

**Comment by AnandRP2030** [comment]
Please assign me this issue under Hacktoberfest2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
