### ISSUE TITLE
Add dark mode to the website

### ISSUE THREAD

**Issue by Aakansha-Chavan** [PriyaGhosal/SkillWise#13]
I visited your website it's great and I would like to contribute in it . I want to add dark mode feature in the website. I would like your feedback on my first issue created.

**Comment by PriyaGhosal** [comment]
@Aakansha-Chavan 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
