### ISSUE TITLE
Add a navigation button to Copyright Documentation in Footer

### ISSUE THREAD

**Issue by kanduru-abhiram** [PriyaGhosal/SkillWise#134]
Hello @PriyaGhosal,

The footer can be upgraded and please add a navigation button to Copyright documentation in the footer under Legal which gives easy navigation to layman users.

Kindly assign me this issue under Hacktoberfest 2024.

![image](https://github.com/user-attachments/assets/22a77b92-89b5-4c47-bfbf-25d82952b165)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by kanduru-abhiram** [comment]
As the pull request was merged under Hacktoberfest2024, please close the issue under Hacktoberfest2024.
