### ISSUE TITLE
Improve Search input box Ui

### ISSUE THREAD

**Issue by shivamnayak201019** [PriyaGhosal/SkillWise#135]
Hello @PriyaGhosal,

I have improved the search input box Ui of Index.html, kindly find the improved version Ui in Attachment
![Improved Search input box ui](https://github.com/user-attachments/assets/e8c3802f-e877-40ee-8374-1b34824b1d69)

Kindly assign me this issue under Hacktoberfest 2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
