### ISSUE TITLE
Suggetion for converting the entire code based in ReactJS or NextJS repo

### ISSUE THREAD

**Issue by vundelavamsi** [PriyaGhosal/SkillWise#14]
As the project grows to keep track of the code in a single HTML, JS files make it difficult for the contributors to understand the code base. So I suggest converting the repo into react.js or the next.js.
Creating routes and implementing different features makes it easier for both maintainers and contributors. to keep track of in the open-source organization.

**Comment by PriyaGhosal** [comment]
Hello @vundelavamsi 
Thank you for the suggestion! While React.js and Next.js offer great modularization, we’re keeping the project in HTML, CSS, and JavaScript for now as it's more beginner-friendly. This allows a wider range of contributors, especially those new to coding, to easily participate and learn from the project.
