### ISSUE TITLE
Update "Get a Quote" Button to "Contact Us" for Improved Navigation

### ISSUE THREAD

**Issue by s0wjanyaa** [PriyaGhosal/SkillWise#141]
On the homepage, both "Contact Us" and "Get a Quote" buttons lead to the same page. To avoid redundancy, replacing the "Get a Quote" button with the "Contact Us" option will streamline the navigation.

@PriyaGhosal Please assign this to me and add the 'Hacktoberfest' label.

![homepage](https://github.com/user-attachments/assets/67256f7a-46c9-4edf-81e7-482d54829181)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Bridgetamana** [comment]
Is this stiil up for grabs?

**Comment by Kawaljeet-943** [comment]
Hi @PriyaGhosal ! If this issue is no longer assigned, I'd love to take it. Could you please assign it to me? Thanks!

**Comment by anirudh-why** [comment]
please assign this issue to me

**Comment by Karthikgouda15** [comment]
Please assign issue this to me to update a "Get quote "  button to  "Contact us "

**Comment by omkar7176** [comment]
I'm happy to contributing in for contributing for this issue, so please assign me this issue.
Thank you !
