### ISSUE TITLE
Register Today button is not visible in Dark mode

### ISSUE THREAD

**Issue by manthanmk66** [PriyaGhosal/SkillWise#143]
The "Register Today" button is not visible when the application is in dark mode. This issue prevents users from accessing an important call-to-action.

![image](https://github.com/user-attachments/assets/79f4df35-52a2-4508-bcb4-33eb2fab01e2)

**Comment by PriyaGhosal** [comment]
@manthanmk66 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by abhagangwar712** [comment]
Hello @PriyaGhosal I want to resolve this issue so that the looks of the button elevate in the dark mode as well.
