### ISSUE TITLE
Repositioning of "Search" and "Start Free Trial" Buttons in Navigation Bar

### ISSUE THREAD

**Issue by sainKunal** [PriyaGhosal/SkillWise#149]
Repositioning of "Search" and "Start Free Trial" Buttons in Navigation Bar

## Issue Description
The current positioning of the "Search" and "Start Free Trial" buttons in the navigation bar is not optimal. Their placement affects the overall aesthetics and usability of the interface, making it difficult for users to locate these important features.

## Observations
- The "Search" button appears cluttered and lacks prominence.
- The "Start Free Trial" button is not visually distinct, which may lead to lower conversion rates.
- User feedback indicates that these buttons are hard to find, impacting the overall user experience.

## Proposed Changes
1. **Repositioning**
   - Move the "Search" button to a more prominent location for better visibility.
   - Position the "Start Free Trial" button in a distinct area, potentially using a contrasting color to draw attention.

2. **Enhancements**
   - Consider improving the button styles (colors, padding, hover effects) to make them more engaging and user-friendly.

##Screenshot
![Screenshot 2024-10-02 223918](https://github.com/user-attachments/assets/ec5f3e27-6707-49b9-a820-bb4d38dddf58)

## Impact
Addressing this issue could lead to:
- Improved user experience and navigation.
- Increased visibility and usage of key features like search and free trial sign-up.

**Comment by sainKunal** [comment]
Hey Can you Assign This Issue to Me

**Comment by PriyaGhosal** [comment]
@sainKunal Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
