### ISSUE TITLE
Navbar taking too much space on the page !

### ISSUE THREAD

**Issue by SiddhanthKapoor** [PriyaGhosal/SkillWise#15]
The navigation bar at times hinders with the content of the pages and should be made translucent so that it does not obstructs
the website contents .

The image attached below shows what happens when we navigate to the About Us section using Footer Links.
I would like to work on this issue !

![Screenshot from 2024-09-29 00-43-22](https://github.com/user-attachments/assets/8e21bb2b-823d-4424-9d70-8075449f62e3)

**Comment by PriyaGhosal** [comment]
Hello @SiddhanthKapoor 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Utkarsh-Aggarwal** [comment]
please assign this issue to me @PriyaGhosal
