### ISSUE TITLE
Nav bar issue

### ISSUE THREAD

**Issue by vishalgupta8982** [PriyaGhosal/SkillWise#151]
Hey, i just see your website your website nav bar not looking that much good i want to improve it ?

**Comment by PriyaGhosal** [comment]
@vishalgupta8982 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
