### ISSUE TITLE
Issue : Create New Blog Section Page with Detailed Research and Design Implementation.

### ISSUE THREAD

**Issue by Arjun11012** [PriyaGhosal/SkillWise#156]
Hello @PriyaGhosal ,

I would love to Design and implement a new Blog section for the website. This section should provide a platform to showcase blog posts and articles, featuring topics that are relevant and insightful for users.

1. Creating a new page dedicated to blog posts with a user-friendly layout.
2. Researching and compiling content for the blog posts, ensuring it is well-organized and insightful.
3. Designing a clean and engaging UI for the blog, ensuring consistency with the rest of the website's design.
4. Making sure to follow any design guidelines and maintain consistency with the overall website branding.
5. Adding Blog Post Ratings/Like System : Add a rating or like system so users can show appreciation for articles, which can help highlight popular content.
6. Dark Mode Support : Providing an option for users to toggle between light and dark mode for better readability and user experience.

Kindly assign me this issue under Hacktoberfest 2024.

![image](https://github.com/user-attachments/assets/5ca39bbd-f688-48c1-9968-455c67121d05)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
