### ISSUE TITLE
Enhance User Experience: Add Hover Effect to Links in 'Links and Legal' Section

### ISSUE THREAD

**Issue by VanshChitransh** [PriyaGhosal/SkillWise#16]
### Description
The links within the "Links and Legal" section currently do not feature a hover effect. Implementing a hover effect would significantly enhance the user experience by providing clear visual feedback during user interaction.

### Screenshots
![Screenshot from 2024-09-29 02-55-27](https://github.com/user-attachments/assets/30039b78-0a4e-467b-be3f-e65600897493)

### Additional Notes
- This enhancement is intended to elevate the overall user interface and accessibility of the application.
- Your insights and suggestions on this issue are welcome!

**Comment by VanshChitransh** [comment]
@PriyaGhosal i would like to work on this issue.

**Comment by PriyaGhosal** [comment]
Hello @VanshChitransh 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
