### ISSUE TITLE
Enhance Navbar Design for Better Visual Separation from Hero Section

### ISSUE THREAD

**Issue by vikrant0563** [PriyaGhosal/SkillWise#17]
The current design of the navbar on the homepage blends in with the hero section, making it difficult to distinguish between the two areas. To improve the visual experience and usability, I propose enhancing the navbar's style to make it more distinct and attractive.

Kindly assign me this issue under Hacktoberfest 2024

**Comment by PriyaGhosal** [comment]
@vikrant0563 This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
