### ISSUE TITLE
Add hover effect on linkedln icon

### ISSUE THREAD

**Issue by AnshVerma04** [PriyaGhosal/SkillWise#176]
![Screenshot (4)](https://github.com/user-attachments/assets/f2572a73-b442-40eb-b8c3-b9f4e59698fa)

Hover Effect is not Working on Linkedln icon so I want to fix it.
I would like to contribute by fixing these issue.

Please assign me this issue.

**Comment by Neelesh19634** [comment]
Hover Effect is not Working on Linkedln icon so I want to fix it.
I would like to contribute by fixing these issue.

Please assign me this issue.

**Comment by AnshDwivedi03** [comment]
Hey @PriyaGhosal i have done necessary changes and it is working now can you merge my pr
