### ISSUE TITLE
Fix the SkillWise Logo in Dark Mode

### ISSUE THREAD

**Issue by UdaySharmaGitHub** [PriyaGhosal/SkillWise#179]
Please assign me this issues under Hacktoberfest 2024
Logo Having a background which make looks odd in dark theme

![image](https://github.com/user-attachments/assets/4550aedd-0daa-4b08-b917-112516b078cf)

**Comment by abhagangwar712** [comment]
Hello @PriyaGhosal , please assign me this issue to make the logo look more effective in darkmode.
![Screenshot 2024-10-03 223143](https://github.com/user-attachments/assets/71d249fd-5f6b-444f-9e30-fe9a6ebee320)
