### ISSUE TITLE
Add Feedback Section to the website 

### ISSUE THREAD

**Issue by KanwalpreetSingh1823** [PriyaGhosal/SkillWise#18]
I would like to contribute in your website . I want to add Feedback Section in the website. I would like your feedback on my first issue created.

**Comment by PriyaGhosal** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by swamimalode07** [comment]
![image](https://github.com/user-attachments/assets/0a28e5ca-9ed6-4654-8039-308ed56f72d8)
 Added a Feedback Form to the Website , should i make a pull request? do you like it
