### ISSUE TITLE
Enhance ''Students; Courses; Learning Hours; visitors'' Section with Hover Effects

### ISSUE THREAD

**Issue by sainKunal** [PriyaGhosal/SkillWise#183]
Enhance ''Students; Courses; Learning Hours; visitors'' Section with Hover Effects

## Overview
We aim to improve the visual appeal and interactivity of the "Students' Courses" section on the learning platform. This enhancement will include adding hover effects and other visual adjustments to make the courses more engaging for users.

## Objectives
- **Add Hover Effects**: Implement CSS hover effects for course cards.
- **Enhance Visual Design**: Improve overall aesthetics for better user experience.
- **Increase Engagement**: Make the course options more appealing to encourage user interaction.

### 1. Hover Effects
- **Course Card Elevation**: When hovered over, the course card should slightly elevate (use a box-shadow effect).
- **Color Change**: Change the background color or text color on hover to provide visual feedback.
- **Transition Effects**: Smooth transitions (e.g., `transition: all 0.3s ease;`) for hover effects to enhance user experience.

### 2. Visual Design Improvements
- **Typography**: Update font styles or sizes for better readability.
- **Color Palette**: Consider using a more vibrant color palette that aligns with the overall site theme.
- **Icons**: Add relevant icons to course cards for better representation
##Screenshot
![Screenshot 2024-10-03 134245](https://github.com/user-attachments/assets/2e72a2d9-3340-47e5-a886-8f1c83897883)

**Comment by sainKunal** [comment]
Hey can you Assign this issue to me

**Comment by anshika-75** [comment]
I have created hover effect in courses section and its working properly @sainKunal . Kindly merge my PR for #183

**Comment by sainKunal** [comment]
@anshika-75  I think you misunderstood what i wanted to correct it's my issue assigned to me And I will work on it You should remove your request

**Comment by AnshDwivedi03** [comment]
@sainKunal  i think you have issue she has done fastly and in better way so let the admin merge the pr

**Comment by anshika-75** [comment]
I have created hover effect in courses section and its working properly @PriyaGhosal  . Kindly merge my PR for https://github.com/PriyaGhosal/SkillWise/issues/183

**Comment by sainKunal** [comment]
@anshika-75  The thing Is I was Working on the whole thing she did it only on one or i don't know But Lemme Decide No We will See It should be me who should get it
