### ISSUE TITLE
Uneven design of social sites.

### ISSUE THREAD

**Issue by AnshDwivedi03** [PriyaGhosal/SkillWise#190]
Hey,
I have seen uneven design where some icon is having narrow border and some with sharp
I will resolve the issue
Please assign it to me under Hacktoberfest tag
![Screenshot 2024-10-03 163203](https://github.com/user-attachments/assets/8e2f9c22-7787-46d5-a1e4-9330d34c9a97)

**Comment by harsh0728** [comment]
I can solve this issue Assign me
