### ISSUE TITLE
Updating README.md file 

### ISSUE THREAD

**Issue by Harymo** [PriyaGhosal/SkillWise#2]
There's a need to update the README.md file with the details such as 

-  features of the website, 
- website motto, then some 
- Adding the screenshots of the website. 
- Adding Instructions on how to run the code

**Comment by PriyaGhosal** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by js-hari** [comment]
Hi! I'd also like to work on this issue. Could you please assign it to me?

**Comment by PriyaGhosal** [comment]
Hello  @js-hari
Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
