### ISSUE TITLE
Add Contacts Page

### ISSUE THREAD

**Issue by realvishalrana** [PriyaGhosal/SkillWise#20]
Please assign this issue under hacktoberfest

**Comment by PriyaGhosal** [comment]
@realvishalrana 
Can you please elaborate what you will add in contact page

**Comment by realvishalrana** [comment]
@PriyaGhosal  I will add a contact page where users can enter their email to receive update

![image](https://github.com/user-attachments/assets/91e726cc-dab9-413a-be2d-4f7ef87c1301)

**Comment by PriyaGhosal** [comment]
@realvishalrana Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Nikhileshmauje** [comment]
Hi! I'd like to work on adding the contact page to the website. Could I be assigned to this issue? Thanks!

**Comment by PriyaGhosal** [comment]
@Nikhileshmauje Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by realvishalrana** [comment]
@PriyaGhosal Please review https://github.com/PriyaGhosal/SkillWise/pull/38 this pull request and merge it

**Comment by realvishalrana** [comment]
@PriyaGhosal Please close this
