### ISSUE TITLE
Add "Register Today page "

### ISSUE THREAD

**Issue by swamimalode07** [PriyaGhosal/SkillWise#22]
I would like to add Registration page Where new user can register to the Website , through this it will register a new user

**Comment by PriyaGhosal** [comment]
@swamimalode07 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by swamimalode07** [comment]
![image](https://github.com/user-attachments/assets/97536747-f8fb-4d21-a093-42ccb75fb79e)
I made this Register today page should i will make a pull request
