### ISSUE TITLE
Make the Nav Logo Circle

### ISSUE THREAD

**Issue by swamimalode07** [PriyaGhosal/SkillWise#23]
Kindly! Assign me the task to make the Logo in the Nav-Bar Circle

**Comment by PriyaGhosal** [comment]
@swamimalode07 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by swamimalode07** [comment]
![image](https://github.com/user-attachments/assets/f91ba29e-d971-4ef4-87e5-5f00f4def848)
 this was the existing state of the navbar logo

**Comment by swamimalode07** [comment]
![image](https://github.com/user-attachments/assets/c5797701-7864-46e3-99f0-5b0ce525be29)
 this is how it looks after making it circle , kindly accept this pull request

**Comment by swamimalode07** [comment]
![image](https://github.com/user-attachments/assets/48604545-6228-44cb-a643-f9575e5c9307)
 Done with the register today page , should i make a pull request?
