### ISSUE TITLE
Add Login Page for Users

### ISSUE THREAD

**Issue by HarikeshKS** [PriyaGhosal/SkillWise#24]
Adding a login page that can be further utilized when the backend will be built.
Can you please assign me this under Hacktoberfest?

**Comment by PriyaGhosal** [comment]
@HarikeshKS  Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
