### ISSUE TITLE
Navbar Link Issue: Section Navigation

### ISSUE THREAD

**Issue by Mayursoni1518** [PriyaGhosal/SkillWise#25]
The navbar buttons are not linked to their corresponding sections. The Nav links should be properly configured so that when a navbar button is clicked, it jumps to the relevant section within the website.

**Comment by PriyaGhosal** [comment]
@Mayursoni1518 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
