### ISSUE TITLE
Update Email Form Button Size and Color

### ISSUE THREAD

**Issue by Himmiee** [PriyaGhosal/SkillWise#256]
**Description**
I noticed that the button on the email form is too small and does not match the intended color variant. 

**Expected Behavior**
- The button should have a wider width to enhance usability.
- The button color should align with the specified color variant.

**Current Behavior**
- The button is currently smaller than expected.
- The color does not match the intended design.

Suggested Change
1. Increase the width of the button to improve visibility and usabilit
2. Update the button color to match the correct variant.

 **Additional Information**
-current design

![49CE8BEC-D1CA-43BF-853F-F5505462DAA2_1_201_a](https://github.com/user-attachments/assets/fba1f820-0583-4ea7-9404-cd37687d883f)
![8795DCDC-E009-4836-91AD-C5B20A15BABA_1_201_a](https://github.com/user-attachments/assets/8408851f-4de7-4efa-82e9-18973a53a425)

- proposed change
![A79166AB-2728-494D-AF8B-BA610F2CA5FD_1_201_a](https://github.com/user-attachments/assets/90188077-5324-4126-b95d-6aacc30bcb56)
![9CD2E226-3AB9-48CA-A616-BABC7EB41455_1_201_a](https://github.com/user-attachments/assets/62b4a904-a511-48ab-9523-3d12f5808f13)

**Comment by NAMAN-Github01** [comment]
Please assign it to me

**Comment by TrishaB29** [comment]
Please assign it to me
