### ISSUE TITLE
UI Enhancement with Hover Effects and Animations

### ISSUE THREAD

**Issue by Mayursoni1518** [PriyaGhosal/SkillWise#26]
Enhance the overall UI by adding smooth hover effects and engaging animations.

**Comment by PriyaGhosal** [comment]
@Mayursoni1518 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by harsh0728** [comment]
Assign this issue to me I will solve this

**Comment by Mayursoni1518** [comment]
@harsh0728 I am already working on it
