### ISSUE TITLE
Typo in Image - "Excellent" Misspelled

### ISSUE THREAD

**Issue by js-hari** [PriyaGhosal/SkillWise#27]
![Screenshot 2024-09-28 175052](https://github.com/user-attachments/assets/a3afabe3-7456-4998-b4d0-058326debed6)

1. The word "Excellent" is misspelled in one of the images.
2. "Lorem Ipsum" placeholder text is used instead of meaningful content in a section of the screen.

**Expected Behavior**
1. The word "Excellent" should be spelled correctly.
2. The "Lorem Ipsum" text should be replaced with relevant, meaningful content.

**Actual Behavior**
1. The word is misspelled (e.g., "Exellent" or similar).
2. "Lorem Ipsum" placeholder text is present instead of actual content.

@PriyaGhosal I'd love to work on this issue.

**Comment by VanshChitransh** [comment]
@PriyaGhosal I would love to work on this issue.

**Comment by PriyaGhosal** [comment]
@js-hari Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by PriyaGhosal** [comment]
@VanshChitransh  Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
