### ISSUE TITLE
Footer Misalignment and UI Disruption on Different Screens

### ISSUE THREAD

**Issue by js-hari** [PriyaGhosal/SkillWise#28]
![Screenshot 2024-09-28 175254](https://github.com/user-attachments/assets/b78b508a-c056-493a-9717-b786d4520cfe)
![Screenshot 2024-09-28 175421](https://github.com/user-attachments/assets/4cdfb273-2da3-4214-afb8-4b29f4327365)

The footer section on multiple screens, including both normal and responsive views, is misaligned or improperly structured. This causes a disruption in the overall user interface (UI), affecting the visual consistency and user experience.

**Expected Behavior**
1. The footer should be consistently aligned and positioned across all screens, ensuring a smooth user experience.
2. On responsive screens, the footer should adapt properly to the screen size without breaking the layout.

**Actual Behavior**
1. The footer is misaligned or positioned incorrectly, leading to a cluttered interface.
2. On smaller screens (e.g., mobile devices), the footer appears out of place and gets misaligned.

**Suggested Fix**
1. I propose restructuring the footer's layout to ensure consistency across all screens (normal and responsive). This may involve:
2. Adjusting the CSS for the footer to maintain proper alignment.
3. Ensuring responsive behavior with media queries or other techniques.

Once this issue is assigned to me, I would be happy to work on a solution to fix the footer's alignment and improve the UI consistency.

**Comment by PriyaGhosal** [comment]
@ Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
