### ISSUE TITLE
Backend Development / Integration

### ISSUE THREAD

**Issue by Potato-29** [PriyaGhosal/SkillWise#29]
Hey @PriyaGhosal, do you need backend development for this project, I'd be happy to work on something like this :)

**Comment by js-hari** [comment]
Hi @PriyaGhosal , I'd also like to collaborate in the backend development if its fine with @Potato-29 .

**Comment by PriyaGhosal** [comment]
@Potato-29 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by PriyaGhosal** [comment]
@Potato-29 Do you want to collaborate with @js-hari

**Comment by Potato-29** [comment]
Sure @PriyaGhosal, I'll be happy to collab. On a side note, can we discuss the backend structure so we can setup a database and get things started

**Comment by PriyaGhosal** [comment]
@js-hariss @Potato-29 
I have assigned you both .Once anyone have some ideas in place, share them here or exchange your Discord IDs for smoother communication. When you're ready, create a pull request .

**Comment by Potato-29** [comment]
Sure give me your discord IDs so I can create a group for easier communication @PriyaGhosal @js-hari

**Comment by js-hari** [comment]
Thanks for setting this up! My Discord ID is hari_js.
Looking forward to the group!

**Comment by PriyaGhosal** [comment]
@js-hari @Potato-29 It's your turn to showcase your skills and shine as contributors. Feel free to reach out to me if you have any questions or need assistance here.

**Comment by Potato-29** [comment]
I've un assigned myself as I don't have the bandwidth right now

**Comment by PriyaGhosal** [comment]
@js-hari What's update .. Are you working on it ??
