### ISSUE TITLE
Old Feature addition : Live Counting 

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/SkillWise#295]
![image](https://github.com/user-attachments/assets/c01c0e16-fc3a-45f1-bd23-c679a2743994)
Anyone who can readd this feature to the website I will merge it .

**Comment by kiran1901** [comment]
Hey @PriyaGhosal , I would like to contribute to this. Could you please assign it to me?

**Comment by PriyaGhosal** [comment]
@kiran1901 Yes please

**Comment by kiran1901** [comment]
https://github.com/PriyaGhosal/SkillWise/pull/522

Raised PR for this please review and merge @PriyaGhosal
