### ISSUE TITLE
Adding Testimonials to the website

### ISSUE THREAD

**Issue by swati-mishra07** [PriyaGhosal/SkillWise#30]
@PriyaGhosal 
there will a section of user reviews and ratings which will build trust to users that this website has potential.

**Comment by PriyaGhosal** [comment]
@swati-mishra07 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by muskanyadav1134** [comment]
Can you please assign this to me?
