### ISSUE TITLE
Visiter and course counter

### ISSUE THREAD

**Issue by lord-cyclone100** [PriyaGhosal/SkillWise#32]
Hello @PriyaGhosal 
I would like to add a visiter and courses counter in your website
Pls assign me this task under hacktoberfest

**Comment by PriyaGhosal** [comment]
@lord-cyclone100 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
