### ISSUE TITLE
Adding the Blog section in the website

### ISSUE THREAD

**Issue by iAmDiksha** [PriyaGhosal/SkillWise#33]
@PriyaGhosal 
There should be a **Blog** section in the website. As it is shown in the Navbar but there is no such section. 

Please assign me this issue under **hacktoberfest** 2024.

**Comment by harsh0728** [comment]
I will add the Blog Section. Assign this to me

**Comment by PriyaGhosal** [comment]
@iAmDiksha Thanks for creating the issue in **SkillWise**!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.
- Include the **issue number** in your PR description for better tracking.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@harsh0728 Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
