### ISSUE TITLE
Feedback Modal Appears on Dark Mode Activation

### ISSUE THREAD

**Issue by stutxi** [PriyaGhosal/SkillWise#345]
When dark mode is enabled, a feedback modal unexpectedly appears. This happens without any user interaction or trigger, apart from toggling dark mode. The modal looks out of place and should not appear when dark mode is switched on.

![image](https://github.com/user-attachments/assets/6ac2aaa5-f948-4eb4-b9fc-3b44c4f99873)

**Comment by swarupn17** [comment]
Hey @stutx Please can you assign this task to me. I can do this task.
Thanks!

**Comment by sujalcharati** [comment]
hey @PriyaGhosal , Please can you assign this task to me. I can do this task.
Thanks!
