### ISSUE TITLE
Fix Bug in Dark Mode

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/SkillWise#359]
**Direct create Pull Request I will assign you in issue later**

![image](https://github.com/user-attachments/assets/ccc56c54-ec3b-4381-9ccb-54c1ba3a4390)

**Comment by SiddarthaKarri** [comment]
I made the following changes,
#385 
you can assign me

**Comment by PriyaGhosal** [comment]
@AnishSahani I have quoted above to directly create PR and I will Assign later but no worries there are many issues pending you can work on them .
Happy open-source contributing! 🚀
