### ISSUE TITLE
Adding new courses under Data Science category

### ISSUE THREAD

**Issue by Gauravtb2253** [PriyaGhosal/SkillWise#36]
Hello mam,
I would like to add courses for Data Science category
I will add good UI and content
Please assign me this under Hacktoberfest label

Thank you

**Comment by PriyaGhosal** [comment]
@Gauravtb2253 Thanks for creating the issue in **SkillWise**!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.
- Include the **issue number** in your PR description for better tracking.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Gauravtb2253** [comment]
Hello do you some issues that I can solve
