### ISSUE TITLE
Suggestion: Migrate to a Modern Bundler/React Framework

### ISSUE THREAD

**Issue by tejasbenibagde** [PriyaGhosal/SkillWise#39]
Hi, I would like to propose a migration of the current project structure to use a modern bundler like Webpack, Vite, or Parcel and potentially adopting React to improve maintainability, scalability, and development efficiency.

Reasons for Migration:
 - Modular Code Structure: Using ES6 modules with a bundler would make the codebase easier to manage and scale.
 - Optimized Builds: A bundler can automate the process of minifying CSS and JS, tree-shaking unused code, and optimizing assets for production builds.
 - Live Reloading: Modern bundlers come with a development server that allows for automatic live reloading, which significantly improves the developer experience.
 - Scalability: If the project grows, a framework like React could better handle the dynamic content and UI components. React also offers better state management tools compared to vanilla JavaScript.

Proposed Solution:
 - Start with a Bundler:
Implementing a tool like Vite or Parcel to bundle JS, CSS, and static assets. This can easily be configured to work with the existing HTML/CSS/JS code.
 - (Optional) Migrate to React:
Gradually refactor parts of the project to use React. This would improve the maintainability of the code by adopting a component-based architecture, making it easier to manage complex UIs.
 - Next Steps:
If approved, I’d be happy to contribute by:

Setting up a Vite project to bundle the existing HTML/CSS/JS.
Refactoring parts of the project to use React (if the maintainers agree to this).
Let me know your thoughts!

**Comment by tejasbenibagde** [comment]
@PriyaGhosal  if you like my thoughts please assign me to this task under the hactoberfest2024

**Comment by PriyaGhosal** [comment]
Thank you for the suggestion! While React.js and Next.js offer great modularization, we’re keeping the project in HTML, CSS, and JavaScript for now as it's more beginner-friendly. This allows a wider range of contributors, especially those new to coding, to easily participate and learn from the project.

**Comment by tejasbenibagde** [comment]
Ok I understand.
