### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Harymo** [PriyaGhosal/SkillWise#4]
There two buttons of get started i think one can be removed and maybe replaced with something else 
I have attached the image below 

![get to ](https://github.com/user-attachments/assets/c2f5a5ad-cdd8-4c21-8b8c-ccb5c759bde3)

**Comment by PriyaGhosal** [comment]
Assigned!
Remove two buttons from it

**Comment by PriyaGhosal** [comment]
@Harymo 
Add Free Trial Button removing two Get Started button .
