### ISSUE TITLE
Add FAQ Section to Improve User Experience on SkillWise Website

### ISSUE THREAD

**Issue by SreyaSudheeran** [PriyaGhosal/SkillWise#40]
I would like to propose the addition of a Frequently Asked Questions (FAQ) section to our SkillWise website. This section would address common user queries related to courses, payments, certifications, and technical support, providing users with quick and easy access to essential information.

If approved, I am happy to take the initiative in gathering the most relevant questions and compiling them for the FAQ section. This feature will improve user experience by reducing confusion and providing a central location for addressing common concerns.

@PriyaGhosal I kindly request that this issue be assigned to me and labeled under the Hacktoberfest label. I am excited to contribute and would love to take responsibility for developing this feature.

**Comment by PriyaGhosal** [comment]
@SreyaSudheeran Thanks for creating the issue in **SkillWise**!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.
- Include the **issue number** in your PR description for better tracking.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
