### ISSUE TITLE
Proposal to Add CONTRIBUTING.md to Project

### ISSUE THREAD

**Issue by Mayursoni1518** [PriyaGhosal/SkillWise#42]
I noticed the project lacks a CONTRIBUTING.md file. I'd like to create this file to provide guidelines on contribution standards, pull request procedures, and coding practices. This will help streamline collaboration and ensure consistency across contributions.

**Comment by theCodeCrusaderX** [comment]
please assign me repo to me

**Comment by PriyaGhosal** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
