### ISSUE TITLE
[ BUG ] Contact Us Form - Name Field Validation

### ISSUE THREAD

**Issue by akash70629** [PriyaGhosal/SkillWise#451]
**Description:**

The "Name" field in the Contact Us section should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

**Steps to Reproduce:**

- Navigate to the Contact Us section.
- Enter a name containing symbols or special characters (e.g., "!@#$", "John! Doe") in the Name field.
- Submit the form.

**Expected Result:**

The Name field should display an error message or prevent form submission when symbols or special characters are entered.

**Actual Result:**

The form accepts and submits the input containing symbols or special characters.

![image](https://github.com/user-attachments/assets/8288f35f-ae3b-4f4b-8c08-26e070085799)

**Priority: High**

**Please checkmark the following checklist**

- [x] I ensured that a similar issue is not opened.
- [x] I provided a clear description of the problem.
- [x] I included steps to reproduce the issue.
- [x] I attached relevant context (screenshot).

**Comment by peterdanwan** [comment]
Hello! I would like to try and tackle this issue.

**Comment by akash70629** [comment]
> Hello! I would like to try and tackle this issue. Whoops - never mind, I see that @akash70629 has linked their PR. Sorry about that!

@peterdanwan don't be sorry bro ❤️ let's search for another issue 🤜🏽🤛🏽
