### ISSUE TITLE
ADD ABOUT US PAGE

### ISSUE THREAD

**Issue by Darshan3690** [PriyaGhosal/SkillWise#455]
In this page we add About SkillWise website .
AFTER click about us button we open a about as page.

**Comment by Darshan3690** [comment]
#457 pr

**Comment by shambhavipathak24** [comment]
I would like to add About us . Please assign this to me..

**Comment by PRATYUSH-MISH** [comment]
In this page we add About SkillWise website .
AFTER click about us button we open a about as page.

**Comment by KartikG2** [comment]
Please assign this to me , I would like to add About us  under hacktoberfest 2024

**Comment by naitikhoriya1** [comment]
Please assign this to me

**Comment by omkar7176** [comment]
/@assign me the issue #455
Thank you !
