### ISSUE TITLE
The "Get Started" button appears twice on the page.

### ISSUE THREAD

**Issue by aritroo** [PriyaGhosal/SkillWise#47]
Hello @PriyaGhosal 
I noticed that the "Get Started" button is rendered twice on the webpage, this could be confusing for users and might be a bug. I suggest removing one of the buttons to streamline the design. I would be happy to contribute, please assign me this task under hacktoberfest. 
I had attached the screenshot below.
Thank You

<img width="1441" alt="Screenshot 2024-10-01 at 11 06 02 AM" src="https://github.com/user-attachments/assets/13f12efa-dbf4-46dd-8d99-5a4e6e47b159">

**Comment by PriyaGhosal** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!

**Comment by aritroo** [comment]
Thank you for pointing that out, I appreciate the guidance and will make sure to check the existing issues more carefully next time.
