### ISSUE TITLE
IP TRACKER PAGE

### ISSUE THREAD

**Issue by Swastik200** [PriyaGhosal/SkillWise#48]
DESIGNED USING HTML,CSS AND JS WHICH CAN TRACK IP ADDRESS SHOWING DETAILS OF LOCATION AND IP ADDRESS

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
