### ISSUE TITLE
Adding LinkedIn Social Media Icon 

### ISSUE THREAD

**Issue by blunterdecosta123** [PriyaGhosal/SkillWise#49]
Hey There! @PriyaGhosal
This website is missing a linkedIn social media handle Icon I want to add this icon to the website.Althought you have mention it's name in the website along with other social media handles.
Similarly the icon for facebook and twitter exists but their names are not specified in description i want to change that too 
<img width="1280" alt="Screenshot 2024-10-01 at 11 45 03 AM" src="https://github.com/user-attachments/assets/0fc3688b-5bd8-4df4-9ff6-12b8b966b67b">

So I request you to kindly assign me this issue under Hactoberfest 2024.
Thanking you in Anticipation!!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by blunterdecosta123** [comment]
Hi @PriyaGhosal Hope you will merge the pull requests based on a FCFS manner First come First serve manner to maintain the authencity.

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me under hactoberfest label
