### ISSUE TITLE
search bar issue

### ISSUE THREAD

**Issue by Boobeshkumar56** [PriyaGhosal/SkillWise#492]
i would like to give a perfect alignmet for the searchbar in the home page could you please assign this for me under hacktoberfest
![Screenshot 2024-10-14 192705](https://github.com/user-attachments/assets/ecc1fb3c-a609-4d2d-a6b2-a0e541602712)

**Comment by PRATYUSH-MISH** [comment]
i would like to give a perfect alignmet for the searchbar in the home page could you please assign this for me under hacktoberfest
