### ISSUE TITLE
Issue with the FeedBack Button when in Dark Mode

### ISSUE THREAD

**Issue by Keshav-1803** [PriyaGhosal/SkillWise#495]
**Title:**  
*UI Issue: Feedback Button Not Visible in Dark Mode*

**Description:**  
When the dark mode is turned on, the feedback button is not visible as expected. Instead, the "Feedback" text is displayed on the left side of the screen. This causes a UI inconsistency, and the feedback button does not appear in its usual place, making it hard for users to find. The misplacement of the feedback button also impacts the visual appeal, making the UI look unpolished.

This issue is crucial to fix as it affects the user experience, particularly for users who prefer dark mode.

**Steps to Reproduce:**  
1. Turn on dark mode.  
2. Navigate to any page where the feedback button is usually visible.  
3. Notice that the feedback text appears misaligned on the left side instead of being a visible button.

**Expected Result:**  
The feedback button should remain visible and properly positioned in dark mode, similar to how it appears in light mode.

**Actual Result:**  
The "Feedback" text is misplaced to the left side of the screen and is not styled as a button, making it hard to notice and access.

**Screenshots:**  
<img width="389" alt="Screenshot 2024-10-14 at 9 50 21 PM" src="https://github.com/user-attachments/assets/be7dc572-887c-4fb3-a30e-d088df9e5dae">

**Additional Context:**  
This might be related to a missing or incorrect CSS styling for the feedback button in dark mode.

**Priority:**  
Medium

**Assigned To:**  
I would like to be assigned to this issue and work on it under the context of **HacktoberFest** and **GirlScript Summer of Code (GSSOC)**.

**Comment by Sayantan1024** [comment]
Hello maintainer,

@PriyaGhosal May I please be assigned this issue.

Thanks!
