### ISSUE TITLE
README UPDATE WITH WEBSITE PREVIEW IMAGES

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/SkillWise#499]
### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER

![image](https://github.com/user-attachments/assets/9528c6ba-1e29-46fc-b926-f0aae3991d62)

**Comment by swati-mishra07** [comment]
@PriyaGhosal i want to do this can you assign me this
