### ISSUE TITLE
Correction in Spelling of Word "Terms" in Terms of Use and Terms of Condition

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#5]
![WhatsApp Image 2024-09-27 at 13 52 14_17d64581](https://github.com/user-attachments/assets/f9530956-7089-46a8-9672-6a8cbb3c49a4)

**Comment by PriyaGhosal** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by codeforlifeee** [comment]
@PriyaGhosal  Can you please Provide me with the right format for pull Request..
It would be Helpful

**Comment by blunterdecosta123** [comment]
Hi Priya you can consider me in the queue for this issue if the author is unable to merge it within the specified time duration.
