### ISSUE TITLE
Centering footer content for smaller screens

### ISSUE THREAD

**Issue by Shivaraj2003** [PriyaGhosal/SkillWise#52]
All the links and footer content is left aligned in smaller screens. The website looks cool if they are aligned centrally.
Please assign me this under Hactoberfest 2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Shivaraj2003** [comment]
Thank you
