### ISSUE TITLE
UI/UX Enhancements: Search Button and Course Page Update.

### ISSUE THREAD

**Issue by Mayur-nimkande-20** [PriyaGhosal/SkillWise#525]
### Issue: Improvements to Search Button and UI/UX Course Page

@PriyaGhosal 
I would like to make some changes to the search button on the main screen and also update the UI/UX course page.
Please do assign me this task under #Hacktoberfest 2024.

**Changes to Search Button:**
1. Enhance the design for better visibility.
2. Add a hover effect to improve user interaction.
3. Ensure it aligns with the overall theme of the application.

**Changes to UI/UX Course Page:**
1. Update the layout to make it more user-friendly.
2. Improve the visual aesthetics to align with modern design principles.
3. Ensure that all interactive elements are easily accessible and intuitive.

**Screenshots:**
<img src="https://github.com/user-attachments/assets/11211148-2680-4265-ae1f-e27e855bc14d" width="400">
<img src="https://github.com/user-attachments/assets/668c104a-71dc-44f3-b4d9-f1a6920abe62" width="400">

**Comment by swstkswstk** [comment]
but i guess there is no need of search bar at the home page and it performs no functionality even  if you want work on search bar add in courses tab that would make more sense , 2ndly it is displayed differently in light and dark mode.

**Comment by Mayur-nimkande-20** [comment]
@swstkswstk that's a great suggestion, in course tab on hover effect is only being applied to last course. So i think it can be fixed and ui/ux.html can also be changed to make it more interactive.
