### ISSUE TITLE
The Login/Register button not linked with login page

### ISSUE THREAD

**Issue by prakruthiprasad20** [PriyaGhosal/SkillWise#557]
The Login/Register button not linked with login page. Please assign me this so that I can link the signin.html file using href.

**Comment by prakruthiprasad20** [comment]
Hey @PriyaGhosal , can you please add "gssoc-ext" tag.

**Comment by mailesrsm** [comment]
> The Login/Register button not linked with login page. Please assign me this so that I can link the signin.html file using href.

it is solved check it
