### ISSUE TITLE
Add Box Styling to Navbar Links for Improved Navigation on SkillWise

### ISSUE THREAD

**Issue by piyushshrma** [PriyaGhosal/SkillWise#56]
To enhance navigation clarity and improve the visual structure of the SkillWise website, I propose adding box styling around the navbar links, such as Home, About, Courses, and more. This design enhancement will make the navigation links more distinct, helping users easily identify and access key sections of the site. The box styling will integrate with the existing website theme, ensuring a cohesive design while also boosting user interaction and providing a more organized layout.

Kindly assign me this issue under Hacktoberfest 2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
