### ISSUE TITLE
 Search bar filters content but appends duplicate results on second search click

### ISSUE THREAD

**Issue by sanchitgumber** [PriyaGhosal/SkillWise#566]
**Description**: When using the search bar to search for a specific word, the search successfully filters topics/content on the first click of the search button. However, if you click the search button again without changing the search query, the same results are appended to the filtered list instead of clearing the old list and fetching fresh results.

**Steps to reproduce**:

Enter a word in the search bar.
Click the search button.
Observe that the results are filtered correctly.
Click the search button again without changing the search query.
The same results are appended to the filtered list rather than refreshing the results.

**Expected behavior**: On subsequent clicks of the search button, the old filtered results should be cleared, and only fresh results should be shown.

**Actual behavior**: The previous results are not cleared,  duplicate results are appended to the filtered list.

<img width="1470" alt="Screenshot 2024-10-17 at 5 58 00 PM" src="https://github.com/user-attachments/assets/aff379b5-9784-4579-8a72-cd77765ddf02">

<img width="1470" alt="Screenshot 2024-10-17 at 5 57 42 PM" src="https://github.com/user-attachments/assets/42e69bb4-5763-4ba9-96aa-eecdbad52c22">

**Comment by mokshith-moksh** [comment]
can you assign this issue to me

**Comment by codebysid** [comment]
I'll start with the issue, assign it to me @PriyaGhosal
