### ISSUE TITLE
Enable Navbar Components to Redirect to Specific Sections

### ISSUE THREAD

**Issue by AnkitLuhar** [PriyaGhosal/SkillWise#57]
**Is your feature request related to a problem?**

1>Currently, the navbar components do not link to specific sections of the webpage. This impacts user experience as they have to manually scroll through the page, making navigation less intuitive.

**Describe the solution you'd like:**

1>I would like to add functionality where clicking on each navbar component smoothly scrolls the user to the corresponding section on the page. Each section should have a unique ID, and the navbar links will reference these IDs for seamless navigation. The scrolling behavior should be smooth and responsive across all screen sizes (mobile, tablet, and desktop).

here is the screenShot::
![Screenshot (929)](https://github.com/user-attachments/assets/c7bfccd8-59df-4f5a-bd9d-568e352adf45)

**Comment by AnkitLuhar** [comment]
@PriyaGhosal  kindly assign the issue under the hacktoberfest2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
