### ISSUE TITLE
Add a Notification system on submit

### ISSUE THREAD

**Issue by DevGajjar28** [PriyaGhosal/SkillWise#571]
I would like to add a notification system on contact page after details filled and clicked to submit a notification pop up and show.

![image](https://github.com/user-attachments/assets/75fe2d3c-6fc1-45ff-8efc-7071d3f695b8)

like this a text and toast color should be matched to theme.
![image](https://github.com/user-attachments/assets/e336ff91-58d9-469d-a2e8-51a8813729b1)

Assign this issue under Hacktoberfest

**Comment by nevil2006** [comment]
[login.zip](https://github.com/user-attachments/files/17432029/login.zip)
html
