### ISSUE TITLE
Adding the scroll to top button.

### ISSUE THREAD

**Issue by AnkitLuhar** [PriyaGhosal/SkillWise#58]
**Is your feature request related to a problem?** 

1>Users need to scroll manually to the top of the page, which can be inconvenient, especially for longer pages.

**Describe the solution you'd like:**

1>Add a scroll-to-top button that becomes visible when the user scrolls down the page. Clicking the button should smoothly scroll the user back to the top. The button should have a hover effect and fit the overall design of the page.

here is the screenshot:
![Screenshot (931)](https://github.com/user-attachments/assets/04d75c8b-fe3e-4e6d-89c2-a8d98e4f16a4)

**Comment by AnkitLuhar** [comment]
@PriyaGhosal  kindly assign this issue under the hacktoberfest.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
