### ISSUE TITLE
Fix: Navbar in career section is not working:

### ISSUE THREAD

**Issue by SubramanyaKS** [PriyaGhosal/SkillWise#611]
The navbar in career section is not working and also alignment is not correct.
I wanted to fix this issue. can you assign me this issue under hacktoberfest

![image](https://github.com/user-attachments/assets/a59c31ac-c44b-4c84-97d0-3a730780c9a8)

**Comment by mokshith-moksh** [comment]
can I work on this issue

**Comment by SubramanyaKS** [comment]
Hi @mokshith-moksh .

I already done that pull request after that you want include anything you can.
or signup page also has same issue you can do that.

**Comment by SubramanyaKS** [comment]
Hi @PriyaGhosal ,
Please review and update pull request. #612 

Thank you
