### ISSUE TITLE
Make a Read More for View all Categories

### ISSUE THREAD

**Issue by AnkurRam2002** [PriyaGhosal/SkillWise#66]
I would like to  make the view all categories button act as a view more button which on being clicked expands the section to show more categories. Can u pls assign this under hacktoberfest

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
