### ISSUE TITLE
Fixing a naming bug 

### ISSUE THREAD

**Issue by AnkurRam2002** [PriyaGhosal/SkillWise#67]
There area two course categories named data science. Can i resolve the bug. Can u assign me the bug under hacktoberfest

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
