### ISSUE TITLE
Add more content and hover effect to the "Register Today" section

### ISSUE THREAD

**Issue by Nikhileshmauje** [PriyaGhosal/SkillWise#68]
![skillwise_firstIssue](https://github.com/user-attachments/assets/d3552094-2a67-4756-8b70-0d394dc393d1)

I'd like to enhance the 'Register Today' section by adding more descriptive content to make it more informative and engaging. Additionally, I plan to implement a hover effect on the 'Register Today' button for better user interaction and UI improvement. Could you please assign this issue to me? Thanks!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
