### ISSUE TITLE
Add Search Bar Feature for Easy Navigation

### ISSUE THREAD

**Issue by AyushKhatri-Dev** [PriyaGhosal/SkillWise#69]
I’d like to suggest adding a search bar at the top of the website with a placeholder like "What do you want to learn...". This will help students easily search for specific topics or courses without having to browse the entire site.

Benefits:
Quicker access to relevant content.
Improved user experience by simplifying navigation.
I would be happy to work on this feature. Please assign me this issue so I can get started.

Thanks!

**Comment by UdaySharmaGitHub** [comment]
assign me this issues

**Comment by UdaySharmaGitHub** [comment]
PR raised please Accept
Add Search Bar Feature for Easy Navigation.
Search bar matching with the theme and Device Responsive

Desktop View
![Screenshot 2024-10-01 213911](https://github.com/user-attachments/assets/1ff032ed-8570-4663-a8d4-e305e970b7df)

Mobile View
![Screenshot 2024-10-01 213927](https://github.com/user-attachments/assets/74646aee-9b4a-4d18-9f39-142368c56b80)

**Comment by AyushKhatri-Dev** [comment]
I am first. And I can make better so assign me this

**Comment by PriyaGhosal** [comment]
@UdaySharmaGitHub Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by AyushKhatri-Dev** [comment]
Hi @PriyaGhosal

I wanted to let you know that I have successfully resolved the issue regarding the search bar. The new implementation is not only functional but also significantly improved. Here are a few points:

Enhanced Functionality: The search bar is now more efficient and user-friendly.
Design Improvement: It aligns perfectly with the existing theme of the project, making it look cohesive.
Responsiveness: The new search bar is fully responsive, ensuring a great experience across all devices.
Please take a look at the changes in the pull request. I believe this enhancement will greatly benefit the project!

Thank you for your time!
