### ISSUE TITLE
Create a flappy bird game

### ISSUE THREAD

**Issue by Swastik200** [PriyaGhosal/SkillWise#70]
Using html,css and js will design a flappy bird game in which we have to control a tiny bird pass those hurdles to win else game over

**Comment by farihaNaqvi** [comment]
@Swastik200 can you assign this to me.

**Comment by PriyaGhosal** [comment]
@Swastik200 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Swastik200** [comment]
Just game using js

**Comment by farihaNaqvi** [comment]
@PriyaGhosal can you let me know if this issue need to be completed or not?

**Comment by PriyaGhosal** [comment]
@Swastik200 @farihaNaqvi  This is Not at all adding value to the website. Find another issue or feature to contribute to. Thank you!

**Comment by Swastik200** [comment]
Okay
