### ISSUE TITLE
ADD VIDEO OF WEBSITE IN WEBSITE PREVIEW IN README 

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/SkillWise#724]
### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER

FIRST PUT VIDEO OF WEBSITE SCROLLING TILL FOOTER FOLLOWED BY UPDATED IMAGES OF WEBSITE

![image](https://github.com/user-attachments/assets/c7ba51a6-8d97-476e-9210-58e0d5910b6e)

**Comment by sadique-2004** [comment]
I can do in just an hour so please assign me this task
