### ISSUE TITLE
Hi, @PriyaGhosal

### ISSUE THREAD

**Issue by Sumit1911** [PriyaGhosal/SkillWise#73]
I would like to enable the "Get Started Now" button which will redirect to a separate page. This new page will display relevant content or actions for users to begin their journey with SkillWise.

Proposed Implementation:
*Implement a redirect from the "Get Started Now" button to a new page.
*Display introductory content or a call-to-action on the new page to guide users.

Design & Functionality:
*Ensure the new page follows the website’s design guidelines.

**Comment by Sumit1911** [comment]
Would you please assign me this task under the Hacktoberfest 2024 tag

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
