### ISSUE TITLE
Invalid placeholder

### ISSUE THREAD

**Issue by Sabeerwaqas** [PriyaGhosal/SkillWise#768]
Hello There,

While I was going through your website, I found an invalid placeholder on your signup page. The placeholder of the "Full Name" field would be "Create you full name" instead of "Create your username". Also, all four placeholders in your signup page fields are inconsistent. They should start with "Enter your" words or "Create" but two of them are starting from "Create your" and remaining two are stat from "Enter your". 

Kindly, assign me this issue in Hacktoberfest 2024.

![image](https://github.com/user-attachments/assets/6878966b-c14b-4f58-9b8f-c60d0fad9f2b)

**Comment by ishu1101** [comment]
please assign it to me
