### ISSUE TITLE
Repetition of the same div bar bug

### ISSUE THREAD

**Issue by yeshwanth-ds** [PriyaGhosal/SkillWise#77]
Currently there are two div bar with the same naming that is "Get Started Now" but here one of them must be changed to "Start Free Trial".

Would you assign me this task under Hacktoberfest tag

![img1](https://github.com/user-attachments/assets/62290241-4871-4128-a15e-e3e4347c6093)

**Comment by PriyaGhosal** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
