### ISSUE TITLE
Changing it into relavent icon

### ISSUE THREAD

**Issue by yeshwanth-ds** [PriyaGhosal/SkillWise#78]
The icon for Finance course must be something related to money or finance rather than Sports icon. I would like to take the responsibility to change this.

Would you assigne me this task under Hacktoberfest tag.

![Screenshot 2024-10-01 223740](https://github.com/user-attachments/assets/cb732ed5-22ef-4c17-b42b-fe41b1d18141)

**Comment by VanshChitransh** [comment]
@PriyaGhosal i am intrested to work on this

**Comment by SupratitDatta** [comment]
@yeshwanth-ds I would like to work on this

**Comment by PriyaGhosal** [comment]
@yeshwanth-ds Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@SupratitDatta @VanshChitransh Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal I have completed this issue and raised a pr

**Comment by shivamnayak201019** [comment]
i am not able to run the project in local repo (i have forked it and cloned it to my folder),
index.js file is missing error

I am new to this, Kindly help
