### ISSUE TITLE
Update Twitter Icon to "X" Logo in Social Media Links

### ISSUE THREAD

**Issue by VanshChitransh** [PriyaGhosal/SkillWise#8]
🐛 Bug Report: Outdated Twitter Logo on Social Media Links

Description:
The current Twitter icon on the SkillWise website is outdated. It still shows the older bird logo, whereas the new "X" logo should be used to reflect the updated branding of Twitter.

Screenshot:
![Screenshot from 2024-09-27 20-13-25](https://github.com/user-attachments/assets/64b6f4a3-3995-4d21-9683-a460b3bd3406)

Steps to Reproduce:
Visit the SkillWise website.
Scroll down to the section with the social media icons (LinkedIn, Twitter, Instagram, etc.).
Observe that the Twitter icon is the old bird logo instead of the new "X" logo.

Expected Behavior:
The Twitter icon should be replaced with the new "X" logo to reflect the platform's rebranding.

Environment:
Browser: Chrome, Safari, Firefox, etc.
Device: Desktop and Mobile

Additional Notes:
Please update the assets to reflect the current Twitter branding. This is important to maintain consistency with the platform's latest design changes.

**Comment by VanshChitransh** [comment]
@PriyaGhosal I would like to work in this issue.

**Comment by PriyaGhosal** [comment]
@VanshChitransh Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by PriyaGhosal** [comment]
@SouravUpadhyay7 Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by VanshChitransh** [comment]
Hi @PriyaGhosal I have solved the issue but i am waiting for hacktoberfest to make the pr. 
![Screenshot from 2024-09-29 23-16-04](https://github.com/user-attachments/assets/38e02b6a-cc30-466a-86b0-bb5744594189)
