### ISSUE TITLE
No LinkedIn icon 

### ISSUE THREAD

**Issue by sainKunal** [PriyaGhosal/SkillWise#80]
Missing LinkedIn Icon

## Description
The LinkedIn icon is missing from the website/application. This issue affects user access to the LinkedIn profile and sharing functionalities.

## Steps to Reproduce
1. Navigate to the homepage.
2. Scroll to the footer (or the section where the LinkedIn icon is supposed to appear).
3. Observe that the LinkedIn icon is not displayed.

## Expected Behavior
The LinkedIn icon should be visible and clickable, directing users to the relevant LinkedIn profile or sharing option.

## Actual Behavior
The LinkedIn icon is not present, which may hinder users from accessing LinkedIn functionalities.

## Screenshots
![Screenshot 2024-10-01 222837](https://github.com/user-attachments/assets/7b8cbfc6-94b7-40f1-b8e5-49e2dd101b2b)

## Additional Information

- **Browser/Device**: (e.g., Chrome on Windows 10, Safari on iOS)
- **Date/Time of Issue**: (e.g., October 1, 2024, at 3:00 PM)
- **Related Links**: (Include any relevant links or references)

**Comment by sainKunal** [comment]
@PriyaGhosal  Can you Assign Me This Issue I can start Working on it then

**Comment by PriyaGhosal** [comment]
@sainKunal 
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
