### ISSUE TITLE
Adding hover and redirecting and pop up to footer items.

### ISSUE THREAD

**Issue by shobhit15082003** [PriyaGhosal/SkillWise#81]
![Screenshot 2024-10-01 233422](https://github.com/user-attachments/assets/d26a363a-eb1a-4237-96e3-0ba87c019dc2)

Here I can add on hover the items will change color and the image will pop up with the insta logo in the center which will take them to the post and also the images will pop up on hover .

**Comment by PriyaGhosal** [comment]
@shobhit15082003 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by shobhit15082003** [comment]
@PriyaGhosal I have raised a PR could you please check it
