### ISSUE TITLE
create a terms of use page

### ISSUE THREAD

**Issue by kavya-r30** [PriyaGhosal/SkillWise#82]
My name is Kavya, and I would like to create a new termsofuse.html file for the "Terms of Use". I plan to include relevant information that supports your website's mission and ensures the content aligns with the design of the index page, making it user-friendly and cohesive. 

Would you please assign me this task under the Hacktoberfest 2024 tag

**Comment by PriyaGhosal** [comment]
@kavya-r30 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
