### ISSUE TITLE
craete a interactive Sign-in page

### ISSUE THREAD

**Issue by yeshwanth-ds** [PriyaGhosal/SkillWise#84]
I would like to create an interactive Sign-in  page such that, when the 'Register Today' anchor is clicked on, it performs an action. Additionally, I want to match its color and background theme with the index.html page.

Would you assigne me this task inder hacktoberfest tag 

![Screenshot 2024-10-01 234955](https://github.com/user-attachments/assets/ebb7375c-822b-4cb2-969b-975b270e25b9)

**Comment by PriyaGhosal** [comment]
@yeshwanth-ds Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal  I ahve compled this task an raised a pr
