### ISSUE TITLE
Remove extra text from Hero Section

### ISSUE THREAD

**Issue by anuragverma108** [PriyaGhosal/SkillWise#840]
![I2](https://github.com/user-attachments/assets/9777a149-c1ce-4ee2-8139-6a513976083e)
Remove the extra text present in the hero section. If anyone wants to contribute it. Tag @PriyaGhosal or @anuragverma108 and we will assign it to you under Hacktoberfest 2024.

**Comment by AnshGulati** [comment]
@anuragverma108 @PriyaGhosal 
I want to be assigned for this issue
/assign

**Comment by BarryByte** [comment]
Please assign this issue to me, Thanks.
