### ISSUE TITLE
Fix the Send Message Button 

### ISSUE THREAD

**Issue by anuragverma108** [PriyaGhosal/SkillWise#841]
![I1](https://github.com/user-attachments/assets/21751b15-b362-483d-b216-f967fad03501)
Fix the width of send message button. If anyone wants to contribute it . Tag @PriyaGhosal or @anuragverma108 and we will assign it to you under Hacktoberfest 2024.

**Comment by aafaris** [comment]
Hi @anuragverma108. I would like to fix this. Please assign it to me, thanks!

**Comment by anuragverma108** [comment]
Start working! @aafaris

**Comment by AkshitBhandariCodes** [comment]
i can fix this issuee
assign me

**Comment by aafaris** [comment]
Please assign @AkshitBhandariCodes instead, thanks!

**Comment by BarryByte** [comment]
@anuragverma108 Please assign this issue to me, Thanks.
