### ISSUE TITLE
Form Visibility Issue in Dark Mode: Incomplete Display of Form Fields

### ISSUE THREAD

**Issue by Jash2606** [PriyaGhosal/SkillWise#846]
### Title of the Issue
 * [✔] **Have you named the issue title clearly and descriptively?**
 * [✔] **Have you searched for existing issues in the project to avoid duplicates?**
 
 ### Description
 The form is not fully visible in dark mode, resulting in some fields not displaying correctly. This affects user readability and accessibility in dark mode.
 
 ### Changes Expected
 Adjustments to the form’s styling in dark mode to ensure all fields are clearly visible and UI-friendly, enhancing the overall user experience.
 
 ### Checklist
 * [✔] I have followed the issue title guidelines.
 * [✔] I have included a clear and detailed description.
 * [✔] I have provided necessary logs, screenshots, or other files.
 * [✔] I am a GSSOC contributor.
 * [✔] I have mentioned related issues or pull requests if any.
 * [✔] I have provided details about the environment where the issue was observed.
![image](https://github.com/user-attachments/assets/c9d37f21-2615-4a0a-9e57-8f1570c65aae)

**Comment by saadii00** [comment]
Hey i would love to work on this may i contribute?

**Comment by Jash2606** [comment]
Hey @PriyaGhosal @anuragverma108 , I'd raised a PR for this issue , Could you review it and Let me Know if any further changes required !
