### ISSUE TITLE
Feat : UI of contact us section in Blog page is not good 

### ISSUE THREAD

**Issue by tanmaysrivastava45** [PriyaGhosal/SkillWise#857]
### Title of the Issue
- [✔] **Have you named the issue title clearly and descriptively?**
- [✔] **Have you searched for existing issues in the project to avoid duplicates?**  

### Description
update UI of contact us section in Blog page 

### Changes Expected
enhancing the CSS of contact us section in blog page 

### Checklist
- [✔] I have followed the issue title guidelines.
- [✔] I have included a clear and detailed description.
- [✔] I have provided necessary logs, screenshots, or other files.
- [✔] I am a GSSOC contributor.
- [✔] I have mentioned related issues or pull requests if any.
- [✔] I have provided details about the environment where the issue was observed.
![image](https://github.com/user-attachments/assets/823616e5-5a03-43fa-8708-ad6ad822fc49)

**Comment by InderParmar** [comment]
Hi @tanmaysrivastava45 , I am eager to work on this issue, can you please assign this issue to me?

**Comment by tanmaysrivastava45** [comment]
@InderParmar  Thank you so much for your interest in this issue! I was already working on it and making progress, but I'll definitely keep you updated if I run into any roadblocks or need assistance. Looking forward to collaborating on future issues!
