### ISSUE TITLE
 Incorrect Positioning of Payment Methods

### ISSUE THREAD

**Issue by sainKunal** [PriyaGhosal/SkillWise#87]
Incorrect Positioning of Payment Methods

## Description
The payment methods section is currently positioned under "Legal" instead of being placed under "Links." This misplacement may lead to confusion for users seeking payment options.

## Steps to Reproduce
1. Navigate to the footer of the website/application.
2. Observe the positioning of the "Payment Methods" section.
3. Note that it appears under "Legal" instead of "Links."

## Expected Behavior
The "Payment Methods" section should be displayed under the "Links" section in the footer for better accessibility and user experience.

## Actual Behavior
The "Payment Methods" section is incorrectly placed under "Legal," which may not align with user expectations.

## Screenshots
![Screenshot 2024-10-02 002040](https://github.com/user-attachments/assets/2c34df36-b695-4192-99a0-5c5c2b83de92)

## Additional Information
- **Browser/Device**: (e.g., Chrome on Windows 10, Safari on iOS)
- **Date/Time of Issue**: (e.g., October 1, 2024, at 3:00 PM)
- **Related Links**: (Include any relevant links or references)

**Comment by sainKunal** [comment]
@PriyaGhosal Can you assign this issue to me

**Comment by PriyaGhosal** [comment]
@sainKunal Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
