### ISSUE TITLE
Updated the styling of ebookhtml

### ISSUE THREAD

**Issue by Ash914027** [PriyaGhosal/SkillWise#883]
changes in the website 

https://github.com/user-attachments/assets/8eda35a5-3668-428f-b8ec-be5ffa6175c4

earlier
![Screenshot 2024-10-28 111742](https://github.com/user-attachments/assets/48321566-6d5a-4a0f-a334-592867c2fc31)

## ✨ General Styling
- **Background color**: Changed to a light neutral (`#fafafa`) for readability. 🌟
- **Text color**: Dark gray (`#2d2d2d`) for contrast with the background. 🎨

## 🔝 Navbar
- **Background color**: Updated to a warmer shade (`#FF6F61`) for better contrast. 🌈
- **Padding and shadow**: Increased padding for spaciousness; added a subtle shadow for depth. 🌥️
- **Link hover color**: Changed `nav-link` hover to a lighter shade (`#ffdecc`) for smoother interactivity. 🖱️

## 📚 Shop Title
- **Font size and color**: Font size increased to `2.2rem`, and color set to match navbar (`#FF6F61`) for brand consistency. 🔗

## 🛍️ Product Grid
- **Grid layout**: Set `max-width` to 1200px for better alignment and responsiveness on larger screens. 📐
- **Product card styling**:
  - **Box shadow** added for depth. 💡
  - **Hover effect**: Each card lifts slightly on hover to boost interactivity. ✨
- **Image styling**: Rounded corners for a polished look. 🖼️
- **Text and button styling**: Updated font sizes, button colors, and hover effects. Button hover color is slightly darker (`#e85b51`) for a noticeable effect. 🎨

## 🦶 Footer
- **Background color**: Aligned with navbar color (`#FF6F61`) for a cohesive look. 🎯
- **Font size**: Adjusted to `0.9rem` to subtly distinguish footer content. 📏

---

These changes provide a visually cohesive, interactive, and accessible design while keeping the FAQ and Cart sections as they are.

**Comment by KatalKavya96** [comment]
assign this to me
