### ISSUE TITLE
Dark Mode UI Visibilty and Mode Switching to Dark Mode and Light Mode

### ISSUE THREAD

**Issue by srpriyanshi6** [PriyaGhosal/SkillWise#886]
The Web-app is in light mode, considering the current UI.
There is no option to switch between Dark Mode and Light Mode, which limits accessibility and usability for users who prefer one mode over the other.
I would like to work on this feature. Kindly assign me this issue @PriyaGhosal and @anuragverma108 with the labels hacktoberfest, hacktoberfest-accepted.

**Comment by KatalKavya96** [comment]
assign this to me
