### ISSUE TITLE
Issue: Add a Separate Copyright Policy Page

### ISSUE THREAD

**Issue by anuragverma108** [PriyaGhosal/SkillWise#9]
Hello @PriyaGhosal , 

To comply with legal standards and protect the intellectual property rights associated with the content on Skill Wise, I propose the addition of a dedicated Copyright Policy page. This page should outline the platform's policies on copyright infringement, guidelines for content usage, and procedures for reporting violations. This will ensure transparency for users and contributors, reinforcing the platform’s commitment to respecting and safeguarding creators' rights.

Kindly assign me this issue under Hacktoberfest 2024

**Comment by PriyaGhosal** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
