### ISSUE TITLE
Adding new courses under UI/UX Design 

### ISSUE THREAD

**Issue by yeshwanth-ds** [PriyaGhosal/SkillWise#93]
I would like to add courses like Google UX Design Professional Certificate, UI/UX Design Specialization by CalArts, Interaction Design Specializatio, etc.. when clicked on UI/UX Design block.
![Screenshot 2024-10-02 014131](https://github.com/user-attachments/assets/f5e20494-fee1-437b-adad-1192ca2bfa48)

**Comment by PriyaGhosal** [comment]
@yeshwanth-ds Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal task completed raised PR

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal  I have complet the task and raised PR #234  
After reviewing it assign with apporiate level tag
