### ISSUE TITLE
Enhancement: Fix "View Categories" Button to Open Categories Page and Implement Functionality

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#95]
Enhance the functionality of the "View Categories" button on the website.
Current implementation does not open the categories page when clicked.
Tasks include:
Debugging the button's click event.
Ensuring it navigates users to the appropriate categories page.
Implementing necessary UI changes to improve user experience.
Creating the categories page if it does not already exist.
Goal: Provide users with easy access to view and explore different categories effectively.
![image](https://github.com/user-attachments/assets/4ed04139-3349-49b3-b28f-1e4aaa2d45ad)

**Comment by PriyaGhosal** [comment]
@codeforlifeee Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
