### ISSUE TITLE
Enhance the functionality of the "View All Courses" button on the website.

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#97]
Current implementation does not open the courses page when clicked.
Tasks include:
Debugging the button's click event.
Ensuring it navigates users to the appropriate courses page.
Implementing necessary UI changes to improve user experience.
Creating the courses page if it does not already exist.
Goal: Provide users with easy access to view and explore all available courses effectively.
![image](https://github.com/user-attachments/assets/acf23e19-1180-4683-8509-b05078683355)

**Comment by PriyaGhosal** [comment]
@codeforlifeee Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
