### ISSUE TITLE
The current heading "Legal" in the website footer will be replaced with "Consumer Information" for better clarity and user understanding.

### ISSUE THREAD

**Issue by codeforlifeee** [PriyaGhosal/SkillWise#99]
![image](https://github.com/user-attachments/assets/d947d77a-927f-4f43-b3c1-efd40e72b116)
Updating the heading in the website footer to "Consumer Information."
Ensuring the change is reflected across all relevant pages.
Verifying that the new heading accurately represents the content within the section.
Goal: Improve user experience by providing a clearer and more descriptive heading that enhances understanding of the information presented.

**Comment by sammyifelse** [comment]
![Screenshot 2024-10-02 104126](https://github.com/user-attachments/assets/156229ed-5e6d-4e5d-8d30-b5bbcba3dbe9)
Changes i have made to update _Legal_ to _Consumer Information_.Kindly accept the PR.

**Comment by codeforlifeee** [comment]
@sammyifelse 
The issue will firstly be assigned to the person who has raised it.. and it will be tagged under the tag of hacktoberfest,and some other tags..and if the person fails to resolve the issues raised by himself/herself then it will be open to all..This is Code of Conduct for this Repository.
so first raise an issue.
wait for the issue would be assigned to you by maintainer of repo
then resolve it within duration of 7 days 
Follow this..

**Comment by sammyifelse** [comment]
Please assign me under HacktoberFest

**Comment by codeforlifeee** [comment]
@PriyaGhosal 
It is actually a abide of rules the one who have raised the issue will be assigned..so do raise some new issue and wait for maintainer to assign to you.. Please look into the matter.

**Comment by PriyaGhosal** [comment]
@codeforlifeee Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@sammyifelse Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by swati-mishra07** [comment]
@PriyaGhosal issue #182   i will be modified  consumer information to company to visuaize the exact things 
can you assign this to me .
![Screenshot (14)](https://github.com/user-attachments/assets/42301a56-71a3-411d-97db-55c43d302461)
